### ISSUE TITLE
Problem with instruction 

### ISSUE THREAD

**Issue by jbiousse** [Alignak-monitoring-contrib/alignak-checks-mongodb#2]
It's the wrong document, "elasticsearch" in mongodb 

Also  : pip install alignak-checks-mongodb not work cause there is no package 

```
Could not find a version that satisfies the requirement alignak-checks-mongodb (from versions: )
No matching distribution found for alignak-checks-mongodb
```

**Comment by mohierf** [comment]
Fixed in the most recent release. See #3 and release 1.1.0
